server:
  port: 5100

logging:
  level:
    root: INFO
    prj.yong.first: DEBUG

swagger:
  authorization:
    headers: X-Api-Key, X-Forwarded-For

springdoc:
  swagger-ui:
    urls:
      - name: sample1
        url: http://localhost:1001/sample1/v3/api-docs
      - name: sample2
        url: http://localhost:1002/sample2/v3/api-docs
      - name: sample3
        url: http://localhost:1003/sample3/v3/api-docs

spring:
  cloud:
    gateway:
      routes:
        # Route Health Check
        - id: route-health-check
          uri: no://op
          predicates:
            - Path=/health
            - Method=GET

        # Route Swagger
        - id: route-swagger-sample1
          uri: http://localhost:1001
          predicates:
            - Path=/sample1/v3/api-docs
            - Method=GET
          filters:
            - IpFilter
        - id: route-swagger-sample2
          uri: http://localhost:1002
          predicates:
            - Path=/sample2/v3/api-docs
            - Method=GET
          filters:
            - IpFilter
        - id: route-swagger-sample3
          uri: http://localhost:1003
          predicates:
            - Path=/sample3/v3/api-docs
            - Method=GET
          filters:
            - IpFilter

        # Route System
        - id: route-sample1
          uri: http://localhost:1001
          predicates:
            - Path=/sample1/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - IpFilter
        - id: route-sample2
          uri: http://localhost:1002
          predicates:
            - Path=/sample2/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - IpFilter
        - id: route-sample3
          uri: http://localhost:1003
          predicates:
            - Path=/sample3/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - IpFilter

filter:
  module-test-server:
    ip: 127.0.0.1/32,127.0.0.1/16,127.0.0.1